"use client";
import { useState, useEffect, useCallback } from "react";
import { motion, Reorder } from "framer-motion";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Plus, Sparkles, GripVertical, Trash2, Play, Save, FileText, Loader2, CheckCircle2 } from "lucide-react";

interface TourStep { id: string; title: string; description: string; targetArea: string; position: "top" | "bottom" | "left" | "right"; }
interface Tour { id: string; title: string; description: string; steps: TourStep[]; assignedTo: number; completed: number; createdAt: string; }
function loadTours(): Tour[] { if (typeof window === "undefined") return []; const raw = localStorage.getItem("trainingwheels_tours"); return raw ? JSON.parse(raw) : []; }
function saveTours(tours: Tour[]) { localStorage.setItem("trainingwheels_tours", JSON.stringify(tours)); }

export default function TourBuilderPage() {
  const params = useParams(); const tourId = params.id as string;
  const [tour, setTour] = useState<Tour | null>(null);
  const [steps, setSteps] = useState<TourStep[]>([]);
  const [manualText, setManualText] = useState("");
  const [isParsing, setIsParsing] = useState(false);
  const [parseResult, setParseResult] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  useEffect(() => { const tours = loadTours(); const found = tours.find(t => t.id === tourId); if (found) { setTour(found); setSteps(found.steps || []); } }, [tourId]);
  const addStep = () => { setSteps([...steps, { id: Date.now().toString(36), title: "", description: "", targetArea: "", position: "bottom" }]); };
  const updateStep = (id: string, field: keyof TourStep, value: string) => { setSteps(steps.map(s => s.id === id ? { ...s, [field]: value } : s)); };
  const deleteStep = (id: string) => { setSteps(steps.filter(s => s.id !== id)); };
  const parseManual = useCallback(async () => { if (!manualText.trim()) return; setIsParsing(true); setParseResult(null); try { const res = await fetch("/api/parse-manual", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: manualText, existingSteps: steps.length }) }); const data = await res.json(); setParseResult(data.raw); if (data.steps?.length) { const newSteps = data.steps.map((s: any) => ({ id: Date.now().toString(36) + Math.random().toString(36).slice(2,6), title: s.title, description: s.description, targetArea: s.targetArea || "", position: "bottom" as const })); setSteps([...steps, ...newSteps]); } } catch {} finally { setIsParsing(false); } }, [manualText, steps]);
  const saveTour = () => { const tours = loadTours(); saveTours(tours.map(t => t.id === tourId ? { ...t, steps } : t)); if (tour) setTour({ ...tour, steps }); setSaved(true); setTimeout(() => setSaved(false), 2000); };
  if (!tour) return <main className="min-h-dvh bg-atmosphere flex items-center justify-center"><p style={{ color: "#94A3B8" }}>Loading...</p></main>;
  return (<main className="min-h-dvh bg-atmosphere">
    <header className="sticky top-4 z-10 mx-4" style={{ paddingTop: "16px" }}><div className="clay-card max-w-5xl mx-auto px-6 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><Link href="/dashboard" className="w-9 h-9 rounded-xl flex items-center justify-center cursor-pointer" style={{ background: "#F1F5F9", border: "2px solid #E2E8F0" }}><ArrowLeft className="w-4 h-4" style={{ color: "#64748B" }} /></Link><div><h1 className="text-lg font-bold" style={{ color: "#1E293B" }}>{tour.title}</h1><p className="text-xs" style={{ color: "#94A3B8" }}>{steps.length} step{steps.length !== 1 ? "s" : ""}</p></div></div><div className="flex items-center gap-3"><Link href={`/tours/${tourId}`} className="flex items-center gap-1.5 px-4 py-2 rounded-2xl text-sm font-semibold cursor-pointer" style={{ background: "#F0FDF4", border: "2px solid #BBF7D0", color: "#16A34A" }}><Play className="w-4 h-4" />Preview</Link><button onClick={saveTour} className="clay-button flex items-center gap-1.5 px-4 py-2 text-sm" style={saved ? { background: "#10B981", borderColor: "#059669" } : {}}>{saved ? <><CheckCircle2 className="w-4 h-4" />Saved</> : <><Save className="w-4 h-4" />Save</>}</button></div></div></header>
    <div className="max-w-5xl mx-auto px-4 pt-8 pb-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-1"><div className="clay-card p-5 sticky top-28"><div className="flex items-center gap-2 mb-4"><Sparkles className="w-5 h-5" style={{ color: "#F97316" }} /><h2 className="font-bold" style={{ color: "#1E293B" }}>AI Step Generator</h2></div><p className="text-xs mb-4" style={{ color: "#94A3B8" }}>Paste your training manual content below. AI will extract step-by-step instructions automatically.</p><textarea value={manualText} onChange={e => setManualText(e.target.value)} placeholder="Paste training manual text here..." className="clay-input w-full mb-3 resize-none text-sm" rows={8} /><button onClick={parseManual} disabled={isParsing || !manualText.trim()} className={`w-full flex items-center justify-center gap-2 py-2.5 text-sm font-semibold rounded-2xl cursor-pointer ${isParsing || !manualText.trim() ? "opacity-50 cursor-not-allowed" : ""}`} style={{ background: "linear-gradient(135deg, #F97316, #EA580C)", color: "#FFFFFF", border: "3px solid #EA580C", boxShadow: "0px 4px 12px rgba(249,115,22,0.2)" }}>{isParsing ? <><Loader2 className="w-4 h-4 animate-spin" />Parsing...</> : <><Sparkles className="w-4 h-4" />Generate Steps</>}</button>{parseResult && <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="mt-4 p-3 rounded-2xl text-xs leading-relaxed" style={{ background: "#F0FDF4", border: "2px solid #BBF7D0", color: "#166534" }}>{parseResult}</motion.div>}</div></div>
      <div className="lg:col-span-2"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-lg" style={{ color: "#1E293B" }}>Tour Steps</h2><button onClick={addStep} className="clay-button flex items-center gap-1.5 px-4 py-2 text-sm"><Plus className="w-4 h-4" />Add Step</button></div>
      {steps.length === 0 ? (<div className="clay-card p-12 text-center"><FileText className="w-10 h-10 mx-auto mb-3" style={{ color: "#CBD5E1" }} /><p className="font-semibold mb-1" style={{ color: "#64748B" }}>No steps yet</p><p className="text-sm mb-4" style={{ color: "#94A3B8" }}>Add steps manually or paste a training manual and let AI generate them</p><button onClick={addStep} className="clay-button inline-flex items-center gap-1.5 px-5 py-2.5 text-sm"><Plus className="w-4 h-4" />Add Your First Step</button></div>) : (<Reorder.Group axis="y" values={steps} onReorder={setSteps} className="space-y-3">{steps.map((step, index) => (<Reorder.Item key={step.id} value={step}><motion.div layout className="clay-card p-5 cursor-grab active:cursor-grabbing"><div className="flex items-start gap-4"><div className="flex items-center gap-2 pt-1"><GripVertical className="w-4 h-4" style={{ color: "#CBD5E1" }} /><div className="step-badge">{index + 1}</div></div><div className="flex-1 space-y-3"><input type="text" placeholder="Step title" value={step.title} onChange={e => updateStep(step.id, "title", e.target.value)} className="clay-input w-full text-sm font-semibold" /><textarea placeholder="Instructions for this step..." value={step.description} onChange={e => updateStep(step.id, "description", e.target.value)} className="clay-input w-full text-sm resize-none" rows={2} /><div className="flex gap-3"><input type="text" placeholder="Target area (e.g. Login button)" value={step.targetArea} onChange={e => updateStep(step.id, "targetArea", e.target.value)} className="clay-input flex-1 text-sm" /><select value={step.position} onChange={e => updateStep(step.id, "position", e.target.value)} className="clay-input text-sm"><option value="top">Tooltip top</option><option value="bottom">Tooltip bottom</option><option value="left">Tooltip left</option><option value="right">Tooltip right</option></select></div></div><button onClick={() => deleteStep(step.id)} className="w-8 h-8 rounded-lg flex items-center justify-center cursor-pointer flex-shrink-0 opacity-40 hover:opacity-100" style={{ background: "#FEF2F2", border: "2px solid #FECACA" }}><Trash2 className="w-3.5 h-3.5" style={{ color: "#EF4444" }} /></button></div></motion.div></Reorder.Item>))}</Reorder.Group>)}
      </div></div></div>
  </main>);
}
